repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.4.0"
  hooks:
  # Prevent giant files from being committed.
  - id: check-added-large-files
  # Check for files with names that would conflict on a case-insensitive filesystem.
  - id: check-case-conflict
  # Check for files that contain merge conflict strings.
  - id: check-merge-conflict
  # Checks for symlinks which do not point to anything.
  - id: check-symlinks
  # Attempts to load all TOML files to verify syntax.
  - id: check-toml
  # Check for debugger imports and py37+ breakpoint() calls in python source.
  - id: debug-statements
