version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .
    - method: pip
      path: ./python_client/
