version: '3'

services:
  mongo:
    image: mongo:4.2
    # MongoDB does not need to be exposed outside the local machine
    # ports:
    #   - 27017:27017
    volumes:
      - ~/slicer_package_manager/db:/data/db

  girder:
    build: .
    # Restrict Girder service to localhost only
    ports:
      - 127.0.0.1:8080:8080
      - '[::1]:8080:8080'
    depends_on:
      - mongo
    volumes:
      - ~/slicer_package_manager/assetstore:/data
    links:
      - mongo
    command: --database mongodb://mongo:27017/girder -H 0.0.0.0

  config:
    build: ./provisioning
    depends_on:
      - mongo
      - girder
    environment:
      - 'GIRDER_HOST=girder'
      - 'GIRDER_PORT=8080'
      - 'GIRDER_ADMIN_NAME=admin'
      - 'GIRDER_ADMIN_PASS=adminadmin'
